### ISSUE TITLE
Moving /v2/api-docs to customised path

### ISSUE THREAD

**Issue by agllno** [springfox/springfox-demos#181]
Hi,

I am using Springfox starter with springboot, I want to move all swagger related files to customised path. I was able to make changes for swagger-ui and it works fine, whereas v2/api-docs is still hosted at http://<endpoint>/context-path>. I tried adding config:
```
springfox:
  documentation:
    swaggerUi:
      baseUrl: /data/api/docs
    swagger:
      v2:
        path: /data/api/docs/v2/api-docs
```
Which did not solve issue. Can you provide me a way to achieve this?
